/-
PCA/Machine.lean

This file defines the SK trace relation on the natural-number codes
from `PCA.Coding`.

The intended operational rules are:

  K x        ↦ K1 x
  K1 x y     ↦ x

  S x        ↦ S1 x
  S1 x y     ↦ S2 x y

  S2 x y z   ↦ (x z) (y z)

The relation is fuelled, but the fuel is only a finite derivation-size
witness. We do not need a realistic cost model.

The constructors are equality-carrying and use explicit parameters.
This avoids relying on autogenerated names after dependent elimination.
-/

import SyntheticComputability.PCA.Coding

namespace PCADev

open Code

/--
`Trace fuel a b c` means that applying code `a` to code `b`
returns code `c`, with finite derivation witness `fuel`.
-/
inductive Trace : N → N → N → N → Prop where
  /-- `K x ↦ K1 x`. -/
  | k_rule
      (fuel a b c : N)
      (hfuel : fuel = 1)
      (ha : a = K)
      (hc : c = K1 b) :
      Trace fuel a b c

  /-- `K1 x y ↦ x`. -/
  | k1_rule
      (fuel a b c x : N)
      (hfuel : fuel = 1)
      (ha : a = K1 x)
      (hc : c = x) :
      Trace fuel a b c

  /-- `S x ↦ S1 x`. -/
  | s_rule
      (fuel a b c : N)
      (hfuel : fuel = 1)
      (ha : a = S)
      (hc : c = S1 b) :
      Trace fuel a b c

  /-- `S1 x y ↦ S2 x y`. -/
  | s1_rule
      (fuel a b c x : N)
      (hfuel : fuel = 1)
      (ha : a = S1 x)
      (hc : c = S2 x b) :
      Trace fuel a b c

  /--
  If `x z ↦ xz`, `y z ↦ yz`, and `xz yz ↦ r`, then

    `S2 x y z ↦ r`.

  The fuel is just the sum of the three sub-derivation witnesses,
  plus one for this rule.
  -/
  | s2_rule
      (fuel a b c fx fy fr x y z xz yz r : N)
      (hfuel : fuel = fx + fy + fr + 1)
      (ha : a = S2 x y)
      (hb : b = z)
      (hc : c = r)
      (hxz : Trace fx x z xz)
      (hyz : Trace fy y z yz)
      (hr : Trace fr xz yz r) :
      Trace fuel a b c

/--
Unbounded application relation.

`App a b c` means that applying `a` to `b` terminates with value `c`.
-/
def App (a b c : N) : Prop :=
  ∃ fuel : N, Trace fuel a b c

namespace Trace

/-- Convenient constructor for `K x ↦ K1 x`. -/
theorem k {x : N} :
    Trace 1 K x (K1 x) :=
  Trace.k_rule 1 K x (K1 x) rfl rfl rfl

/-- Convenient constructor for `K1 x y ↦ x`. -/
theorem k1 {x y : N} :
    Trace 1 (K1 x) y x :=
  Trace.k1_rule 1 (K1 x) y x x rfl rfl rfl

/-- Convenient constructor for `S x ↦ S1 x`. -/
theorem s {x : N} :
    Trace 1 S x (S1 x) :=
  Trace.s_rule 1 S x (S1 x) rfl rfl rfl

/-- Convenient constructor for `S1 x y ↦ S2 x y`. -/
theorem s1 {x y : N} :
    Trace 1 (S1 x) y (S2 x y) :=
  Trace.s1_rule 1 (S1 x) y (S2 x y) x rfl rfl rfl

/-- Convenient constructor for the `S2` rule. -/
theorem s2 {fx fy fr x y z xz yz r : N}
    (hxz : Trace fx x z xz)
    (hyz : Trace fy y z yz)
    (hr : Trace fr xz yz r) :
    Trace (fx + fy + fr + 1) (S2 x y) z r :=
  Trace.s2_rule
    (fx + fy + fr + 1)
    (S2 x y)
    z
    r
    fx
    fy
    fr
    x
    y
    z
    xz
    yz
    r
    rfl
    rfl
    rfl
    rfl
    hxz
    hyz
    hr

/--
The trace relation is functional: a fixed application has at most one result.
-/
theorem functional :
    ∀ {f g a b c d : N},
      Trace f a b c →
      Trace g a b d →
      c = d := by
  intro f g a b c d h
  induction h generalizing g d with
  | k_rule fuel a b c hfuel ha hc =>
      intro h'
      cases h' with
      | k_rule fuel' a' b' d' hfuel' ha' hd =>
          exact hc.trans hd.symm
      | k1_rule fuel' a' b' d' x' hfuel' ha' hd =>
          have hbad : K = K1 x' :=
            ha.symm.trans ha'
          exact False.elim ((K_ne_K1 x') hbad)
      | s_rule fuel' a' b' d' hfuel' ha' hd =>
          have hbad : K = S :=
            ha.symm.trans ha'
          exact False.elim (K_ne_S hbad)
      | s1_rule fuel' a' b' d' x' hfuel' ha' hd =>
          have hbad : K = S1 x' :=
            ha.symm.trans ha'
          exact False.elim ((K_ne_S1 x') hbad)
      | s2_rule fuel' a' b' d' fx' fy' fr' x' y' z' xz' yz' r'
          hfuel' ha' hb' hd hxz' hyz' hr' =>
          have hbad : K = S2 x' y' :=
            ha.symm.trans ha'
          exact False.elim ((K_ne_S2 x' y') hbad)

  | k1_rule fuel a b c x hfuel ha hc =>
      intro h'
      cases h' with
      | k_rule fuel' a' b' d' hfuel' ha' hd =>
          have hbad : K = K1 x :=
            ha'.symm.trans ha
          exact False.elim ((K_ne_K1 x) hbad)
      | k1_rule fuel' a' b' d' x' hfuel' ha' hd =>
          have hx : x = x' :=
            K1_inj (ha.symm.trans ha')
          exact hc.trans (hx.trans hd.symm)
      | s_rule fuel' a' b' d' hfuel' ha' hd =>
          have hbad : S = K1 x :=
            ha'.symm.trans ha
          exact False.elim ((S_ne_K1 x) hbad)
      | s1_rule fuel' a' b' d' x' hfuel' ha' hd =>
          have hbad : K1 x = S1 x' :=
            ha.symm.trans ha'
          exact False.elim ((K1_ne_S1 x x') hbad)
      | s2_rule fuel' a' b' d' fx' fy' fr' x' y' z' xz' yz' r'
          hfuel' ha' hb' hd hxz' hyz' hr' =>
          have hbad : K1 x = S2 x' y' :=
            ha.symm.trans ha'
          exact False.elim ((K1_ne_S2 x x' y') hbad)

  | s_rule fuel a b c hfuel ha hc =>
      intro h'
      cases h' with
      | k_rule fuel' a' b' d' hfuel' ha' hd =>
          have hbad : K = S :=
            ha'.symm.trans ha
          exact False.elim (K_ne_S hbad)
      | k1_rule fuel' a' b' d' x' hfuel' ha' hd =>
          have hbad : S = K1 x' :=
            ha.symm.trans ha'
          exact False.elim ((S_ne_K1 x') hbad)
      | s_rule fuel' a' b' d' hfuel' ha' hd =>
          exact hc.trans hd.symm
      | s1_rule fuel' a' b' d' x' hfuel' ha' hd =>
          have hbad : S = S1 x' :=
            ha.symm.trans ha'
          exact False.elim ((S_ne_S1 x') hbad)
      | s2_rule fuel' a' b' d' fx' fy' fr' x' y' z' xz' yz' r'
          hfuel' ha' hb' hd hxz' hyz' hr' =>
          have hbad : S = S2 x' y' :=
            ha.symm.trans ha'
          exact False.elim ((S_ne_S2 x' y') hbad)

  | s1_rule fuel a b c x hfuel ha hc =>
      intro h'
      cases h' with
      | k_rule fuel' a' b' d' hfuel' ha' hd =>
          have hbad : K = S1 x :=
            ha'.symm.trans ha
          exact False.elim ((K_ne_S1 x) hbad)
      | k1_rule fuel' a' b' d' x' hfuel' ha' hd =>
          have hbad : K1 x' = S1 x :=
            ha'.symm.trans ha
          exact False.elim ((K1_ne_S1 x' x) hbad)
      | s_rule fuel' a' b' d' hfuel' ha' hd =>
          have hbad : S = S1 x :=
            ha'.symm.trans ha
          exact False.elim ((S_ne_S1 x) hbad)
      | s1_rule fuel' a' b' d' x' hfuel' ha' hd =>
          have hx : x = x' :=
            S1_inj (ha.symm.trans ha')
          cases hx
          exact hc.trans hd.symm
      | s2_rule fuel' a' b' d' fx' fy' fr' x' y' z' xz' yz' r'
          hfuel' ha' hb' hd hxz' hyz' hr' =>
          have hbad : S1 x = S2 x' y' :=
            ha.symm.trans ha'
          exact False.elim ((S1_ne_S2 x x' y') hbad)

  | s2_rule fuel a b c fx fy fr x y z xz yz r
      hfuel ha hb hc hxz hyz hr ihxz ihyz ihr =>
      intro h'
      cases h' with
      | k_rule fuel' a' b' d' hfuel' ha' hd =>
          have hbad : K = S2 x y :=
            ha'.symm.trans ha
          exact False.elim ((K_ne_S2 x y) hbad)
      | k1_rule fuel' a' b' d' x' hfuel' ha' hd =>
          have hbad : K1 x' = S2 x y :=
            ha'.symm.trans ha
          exact False.elim ((K1_ne_S2 x' x y) hbad)
      | s_rule fuel' a' b' d' hfuel' ha' hd =>
          have hbad : S = S2 x y :=
            ha'.symm.trans ha
          exact False.elim ((S_ne_S2 x y) hbad)
      | s1_rule fuel' a' b' d' x' hfuel' ha' hd =>
          have hbad : S1 x' = S2 x y :=
            ha'.symm.trans ha
          exact False.elim ((S1_ne_S2 x' x y) hbad)
      | s2_rule fuel' a' b' d' fx' fy' fr' x' y' z' xz' yz' r'
          hfuel' ha' hb' hd hxz' hyz' hr' =>
          have hhead : S2 x y = S2 x' y' :=
            ha.symm.trans ha'
          have hxy : x = x' ∧ y = y' :=
            S2_inj hhead
          have hz : z = z' :=
            hb.symm.trans hb'
          cases hxy.left
          cases hxy.right
          cases hz

          have hxz_eq : xz = xz' :=
            ihxz hxz'
          cases hxz_eq

          have hyz_eq : yz = yz' :=
            ihyz hyz'
          cases hyz_eq

          have hr_eq : r = r' :=
            ihr hr'

          exact hc.trans (hr_eq.trans hd.symm)

end Trace

namespace App

/--
The unbounded application relation is functional.
-/
theorem functional :
    ∀ {a b c d : N},
      App a b c →
      App a b d →
      c = d := by
  intro a b c d hc hd
  cases hc with
  | intro f hf =>
      cases hd with
      | intro g hg =>
          exact Trace.functional hf hg

end App

end PCADev
